apiVersion: v1
kind: Secret
metadata:
  name: photoprism-credentials
  namespace: {{ index . "namespace" }}
type: Opaque
stringData:
  adminPassword: {{ index . "adminPassword" }}
  dbPassword: {{ index . "dbPassword" }}
